# version: '3.8'

services:
  app:
    image: backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    env_file:
      - /backend/.env
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:123456@host.docker.internal:5432/kpi_db
      # - DATABASE_URL=postgres://postgres:123456@db:5432/kpi_db
    # depends_on:
    #   - db

#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 123456
#       POSTGRES_DB: kpi_db
#     volumes:
#       - db_data:/var/lib/postgresql/data

#   adminer:
#     image: adminer
#     ports:
#       - "8080:8080"

# volumes:
#   db_data: